import { useEffect,useMemo,useState } from "react";
import { adjustRewardPoints,getRewardAdminData,listCampaignSubmissions,listReferralProfiles,listReferrals,manageAffiliateProfile,reviewCampaignSubmission,updateRewardPrize,updateRewardProgram,type CampaignReviewCriteria,type CampaignSubmission,type ReferralProfile,type RewardBenefit,type RewardPointEntry,type RewardPrize,type RewardProgram,type RewardSpin,type RewardWallet } from "../lib/api";
import type { Referral } from "../lib/types";

const checks:Array<[keyof CampaignReviewCriteria,string]>=[["socialPostPublic","Publicação social abre sem login"],["socialPostDescribesUse","Publicação relata uso real e benefício"],["linkedinPostPublic","Publicação do LinkedIn está acessível"],["linkedinPostDescribesUse","LinkedIn relata uso real e benefício"],["campaignDisclosureVisible","Divulgação da campanha está visível"],["productFeedbackUseful","Feedback tem exemplos e sugestão útil"],["identityConsistent","Identidade e autoria são consistentes"]];
const emptyCriteria=()=>Object.fromEntries(checks.map(([key])=>[key,false])) as CampaignReviewCriteria;
const date=(value:string|null)=>value?new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(value)):"—";
type RewardsData={programs:RewardProgram[];prizes:RewardPrize[];wallets:RewardWallet[];entries:RewardPointEntry[];spins:RewardSpin[];benefits:RewardBenefit[]};

export function CampaignsPage(){
  const [tab,setTab]=useState<"rewards"|"missions"|"affiliates">("rewards"),[items,setItems]=useState<CampaignSubmission[]>([]),[profiles,setProfiles]=useState<ReferralProfile[]>([]),[referrals,setReferrals]=useState<Referral[]>([]),[rewards,setRewards]=useState<RewardsData>({programs:[],prizes:[],wallets:[],entries:[],spins:[],benefits:[]}),[filter,setFilter]=useState("all"),[search,setSearch]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(""),[criteria,setCriteria]=useState<Record<string,CampaignReviewCriteria>>({}),[notes,setNotes]=useState<Record<string,string>>({});
  const load=async()=>{setError("");try{const [missions,affiliateProfiles,referralRows,rewardData]=await Promise.all([listCampaignSubmissions(),listReferralProfiles(),listReferrals(),getRewardAdminData()]);setItems(missions);setProfiles(affiliateProfiles);setReferrals(referralRows);setRewards(rewardData);}catch(e){setError(e instanceof Error?e.message:String(e));}};
  useEffect(()=>{void load();},[]);
  const visible=useMemo(()=>items.filter(i=>(filter==="all"||i.status===filter)&&(`${i.user_id} ${i.campaign_key}`.toLowerCase().includes(search.toLowerCase()))),[items,filter,search]);
  const review=async(item:CampaignSubmission,approve:boolean)=>{const selected=criteria[item.id]||emptyCriteria(),note=(notes[item.id]||"").trim();if(approve&&!Object.values(selected).every(Boolean)){setError("Marque todos os critérios comprovados antes de aprovar.");return;}if(!approve&&!note){setError("Explique claramente o que precisa ser corrigido.");return;}setBusy(item.id);try{await reviewCampaignSubmission(item.id,approve,note,selected);await load();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy("");}};
  const metrics={available:rewards.wallets.reduce((n,w)=>n+w.available_points,0),issued:rewards.entries.filter(e=>e.points>0).reduce((n,e)=>n+e.points,0),spent:rewards.spins.reduce((n,s)=>n+s.points_spent,0),spins:rewards.spins.length,liability:rewards.benefits.filter(b=>["available","reserved","applied"].includes(b.status)).length};
  return <section><div className="qa-page-header"><div><h1>QA Rewards e afiliados</h1><p>Pontos auditáveis, roleta server-side, benefícios limitados e revisão antifraude.</p></div><button className="qa-btn" onClick={()=>void load()}>Atualizar</button></div>
    {error&&<div className="qa-alert is-error" role="alert">{error}</div>}
    <div className="qa-metrics-grid"><Metric value={metrics.available} label="Pontos disponíveis"/><Metric value={metrics.issued} label="Pontos emitidos"/><Metric value={metrics.spent} label="Pontos consumidos"/><Metric value={metrics.spins} label="Giros"/><Metric value={metrics.liability} label="Benefícios em aberto"/></div>
    <div className="qa-form-row"><button className={`qa-btn ${tab==="rewards"?"primary":""}`} onClick={()=>setTab("rewards")}>Programa e roleta</button><button className={`qa-btn ${tab==="missions"?"primary":""}`} onClick={()=>setTab("missions")}>Evidências e pontos</button><button className={`qa-btn ${tab==="affiliates"?"primary":""}`} onClick={()=>setTab("affiliates")}>Afiliados</button></div>
    {tab==="rewards"?<RewardsManager data={rewards} reload={load}/>:tab==="missions"?<><div className="qa-card"><div className="qa-form-row"><input aria-label="Buscar evidência" placeholder="Buscar usuário ou campanha" value={search} onChange={e=>setSearch(e.target.value)}/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todos</option><option value="pending">Em análise</option><option value="approved">Aprovadas</option><option value="rejected">Ajustes</option></select></div></div>{visible.map(item=>{const selected=criteria[item.id]||emptyCriteria();return <article className="qa-card" key={item.id}><div className="qa-card-header"><div><strong>{item.campaign_key}</strong><div className="qa-dim">{date(item.submitted_at)} · reenvios: {item.resubmission_count||0}</div></div><span className={`qa-badge ${item.status}`}>{item.status}</span></div><p><b>Usuário:</b> <code>{item.user_id}</code></p><p><a href={item.social_post_url} target="_blank" rel="noreferrer">Abrir relato público</a> · <a href={item.linkedin_post_url} target="_blank" rel="noreferrer">Abrir LinkedIn</a></p><div className="qa-review-feedback"><b>Feedback</b><p>{item.product_feedback}</p></div>{item.status!=="approved"?<><fieldset className="qa-review-checklist"><legend>Comprovação obrigatória</legend>{checks.map(([key,label])=><label key={key}><input type="checkbox" checked={selected[key]} onChange={e=>setCriteria(current=>({...current,[item.id]:{...selected,[key]:e.target.checked}}))}/><span>{label}</span></label>)}</fieldset><label className="qa-review-notes">Retorno ao usuário<textarea rows={3} value={notes[item.id]||""} onChange={e=>setNotes(n=>({...n,[item.id]:e.target.value}))}/></label><div className="qa-actions"><button className="qa-btn primary" disabled={busy===item.id} onClick={()=>void review(item,true)}>Aprovar e creditar 60 pontos</button><button className="qa-btn danger" disabled={busy===item.id} onClick={()=>void review(item,false)}>Solicitar ajustes</button></div></>:<div className="qa-alert"><b>Pontos creditados em {date(item.reviewed_at)}</b><p>{item.review_notes}</p></div>}</article>})}</>:<AffiliateManager profiles={profiles} referrals={referrals}/>}</section>;
}
function Metric({value,label}:{value:number;label:string}){return <div className="qa-metric-card"><div className="value">{value}</div><div className="label">{label}</div></div>}

function RewardsManager({data,reload}:{data:RewardsData;reload:()=>Promise<void>}){
  const program=data.programs[0],[busy,setBusy]=useState(""),[adjustUser,setAdjustUser]=useState(""),[adjustPoints,setAdjustPoints]=useState(""),[adjustReason,setAdjustReason]=useState("");
  const updateProgram=async(input:Partial<RewardProgram>)=>{if(!program)return;setBusy("program");try{await updateRewardProgram(program.id,input);await reload();}finally{setBusy("");}};
  const updatePrize=async(prize:RewardPrize,input:Partial<RewardPrize>)=>{setBusy(prize.id);try{await updateRewardPrize(prize.id,input);await reload();}finally{setBusy("");}};
  const adjust=async(e:React.FormEvent)=>{e.preventDefault();const points=Number(adjustPoints);if(!adjustUser||points<=0||!adjustReason.trim())return;setBusy("adjust");try{await adjustRewardPoints(adjustUser,points,adjustReason.trim());setAdjustPoints("");setAdjustReason("");await reload();}finally{setBusy("");}};
  return <><div className="qa-card"><div className="qa-card-header"><div><h2>Kill switch e limites</h2><p className="qa-dim">Ative somente depois da migração e dos testes. Alterações ficam auditadas.</p></div>{program&&<button className={`qa-btn ${program.enabled?"danger":"primary"}`} disabled={busy==="program"} onClick={()=>void updateProgram({enabled:!program.enabled})}>{program.enabled?"Pausar roleta":"Ativar roleta"}</button>}</div>{program&&<div className="qa-form-row"><label>Pontos por giro<input type="number" min="1" defaultValue={program.points_per_spin} onBlur={e=>Number(e.target.value)!==program.points_per_spin&&void updateProgram({points_per_spin:Number(e.target.value)})}/></label><label>Máximo diário por usuário<input type="number" min="1" max="100" defaultValue={program.max_spins_per_user_per_day} onBlur={e=>Number(e.target.value)!==program.max_spins_per_user_per_day&&void updateProgram({max_spins_per_user_per_day:Number(e.target.value)})}/></label></div>}</div>
    <div className="qa-card"><h2>Prêmios e progressão</h2><p className="qa-dim">Os pesos são relativos apenas aos prêmios desbloqueados na faixa do usuário.</p><div className="qa-table-wrap"><table className="qa-table"><thead><tr><th>Prêmio</th><th>Peso</th><th>Pontos vitalícios mínimos</th><th>Concedidos</th><th>Limite global</th><th>Status</th></tr></thead><tbody>{data.prizes.map(p=><tr key={p.id}><td>{p.label_pt}<div className="qa-dim">{p.kind}</div></td><td><input aria-label={`Peso ${p.label_pt}`} type="number" min="1" defaultValue={p.weight} onBlur={e=>Number(e.target.value)!==p.weight&&void updatePrize(p,{weight:Number(e.target.value)})}/></td><td><input aria-label={`Mínimo ${p.label_pt}`} type="number" min="0" defaultValue={p.minimum_lifetime_points} onBlur={e=>Number(e.target.value)!==p.minimum_lifetime_points&&void updatePrize(p,{minimum_lifetime_points:Number(e.target.value)})}/></td><td>{p.awarded_count}</td><td>{p.maximum_global_awards||"Sem limite"}</td><td><button className={`qa-btn ${p.enabled?"danger":""}`} disabled={busy===p.id} onClick={()=>void updatePrize(p,{enabled:!p.enabled})}>{p.enabled?"Desativar":"Ativar"}</button></td></tr>)}</tbody></table></div></div>
    <div className="qa-card"><h2>Ajuste manual auditável</h2><form className="qa-form-row" onSubmit={adjust}><input placeholder="UUID do usuário" value={adjustUser} onChange={e=>setAdjustUser(e.target.value)}/><input type="number" min="1" placeholder="Pontos" value={adjustPoints} onChange={e=>setAdjustPoints(e.target.value)}/><input placeholder="Motivo obrigatório" value={adjustReason} onChange={e=>setAdjustReason(e.target.value)}/><button className="qa-btn primary" disabled={busy==="adjust"}>Creditar</button></form></div>
    <div className="qa-card"><h2>Carteiras e risco</h2><div className="qa-table-wrap"><table className="qa-table"><thead><tr><th>Usuário</th><th>Disponível</th><th>Vitalício</th><th>Gasto</th><th>Dívida/estorno</th><th>Atualizado</th></tr></thead><tbody>{data.wallets.map(w=><tr key={w.user_id}><td><code>{w.user_id}</code></td><td>{w.available_points}</td><td>{w.lifetime_points}</td><td>{w.spent_points}</td><td className={w.debt_points?"qa-danger-text":""}>{w.debt_points}</td><td>{date(w.updated_at)}</td></tr>)}</tbody></table></div></div>
    <div className="qa-card"><h2>Ledger e auditoria recente</h2><div className="qa-table-wrap"><table className="qa-table"><thead><tr><th>Data</th><th>Usuário</th><th>Evento</th><th>Pontos</th><th>Origem</th><th>Status</th></tr></thead><tbody>{data.entries.slice(0,100).map(e=><tr key={e.id}><td>{date(e.created_at)}</td><td><code>{e.user_id}</code></td><td>{e.event_kind}</td><td>{e.points>0?"+":""}{e.points}</td><td>{e.source_type}: {e.source_reference}</td><td>{e.status}</td></tr>)}</tbody></table></div></div></>;
}

function AffiliateManager({profiles,referrals}:{profiles:ReferralProfile[];referrals:Referral[]}){
  const [query,setQuery]=useState(""),[enabled,setEnabled]=useState<Record<string,boolean>>({}),[busy,setBusy]=useState("");const filtered=profiles.filter(p=>`${p.referral_code} ${p.user_id}`.toLowerCase().includes(query.toLowerCase()));
  const toggle=async(profile:ReferralProfile)=>{const current=enabled[profile.user_id]??profile.enabled,reason=window.prompt(current?"Motivo da pausa":"Observação da reativação",profile.internal_notes||"");if(reason===null)return;setBusy(profile.user_id);try{await manageAffiliateProfile(profile.user_id,!current,reason);setEnabled(value=>({...value,[profile.user_id]:!current}));}finally{setBusy("");}};
  return <><div className="qa-card"><input aria-label="Buscar afiliado" placeholder="Buscar código ou usuário" value={query} onChange={e=>setQuery(e.target.value)}/><div className="qa-table-wrap"><table className="qa-table"><thead><tr><th>Código</th><th>Afiliado</th><th>Indicados</th><th>Pagamentos válidos</th><th>Status</th><th>Ação</th></tr></thead><tbody>{filtered.map(profile=>{const rows=referrals.filter(r=>r.referrer_user_id===profile.user_id),active=enabled[profile.user_id]??profile.enabled;return <tr key={profile.user_id}><td><code>{profile.referral_code}</code></td><td><code>{profile.user_id}</code></td><td>{rows.length}</td><td>{rows.filter(r=>r.status==="qualified").length}</td><td>{active?"Ativo":"Pausado"}</td><td><button className={`qa-btn ${active?"danger":""}`} disabled={busy===profile.user_id} onClick={()=>void toggle(profile)}>{active?"Pausar":"Reativar"}</button></td></tr>})}</tbody></table></div></div></>;
}
