import { useEffect, useMemo, useState } from "react";
import { listCampaignSubmissions, listReferralProfiles, listReferrals, manageAffiliateProfile, reviewCampaignSubmission, type CampaignReviewCriteria, type CampaignSubmission, type ReferralProfile } from "../lib/api";
import type { Referral } from "../lib/types";

const checks: Array<[keyof CampaignReviewCriteria,string]> = [
  ["socialPostPublic","Publicação social abre sem login"],
  ["socialPostDescribesUse","Publicação social relata uso real e benefício"],
  ["linkedinPostPublic","Publicação do LinkedIn está acessível"],
  ["linkedinPostDescribesUse","LinkedIn relata uso real e benefício"],
  ["campaignDisclosureVisible","Divulgação da campanha está visível"],
  ["productFeedbackUseful","Feedback tem exemplos e sugestão útil"],
  ["identityConsistent","Identidade e autoria das evidências são consistentes"],
];
const emptyCriteria=()=>Object.fromEntries(checks.map(([key])=>[key,false])) as CampaignReviewCriteria;
const date=(value:string|null)=>value?new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(value)):"—";

export function CampaignsPage() {
  const [tab,setTab]=useState<"missions"|"affiliates">("missions"); const [items,setItems]=useState<CampaignSubmission[]>([]); const [profiles,setProfiles]=useState<ReferralProfile[]>([]); const [referrals,setReferrals]=useState<Referral[]>([]); const [filter,setFilter]=useState("all"); const [search,setSearch]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(""); const [criteria,setCriteria]=useState<Record<string,CampaignReviewCriteria>>({}); const [notes,setNotes]=useState<Record<string,string>>({});
  const load=async()=>{setError("");try{const [missions,affiliateProfiles,referralRows]=await Promise.all([listCampaignSubmissions(),listReferralProfiles(),listReferrals()]);setItems(missions);setProfiles(affiliateProfiles);setReferrals(referralRows);}catch(e){setError(e instanceof Error?e.message:String(e));}};
  useEffect(()=>{void load();},[]);
  const visible=useMemo(()=>items.filter(i=>(filter==="all"||i.status===filter)&&(`${i.user_id} ${i.campaign_key}`.toLowerCase().includes(search.toLowerCase()))),[items,filter,search]);
  const review=async(item:CampaignSubmission,approve:boolean)=>{const selected=criteria[item.id]||emptyCriteria();const note=(notes[item.id]||"").trim();if(approve&&!Object.values(selected).every(Boolean)){setError("Marque todos os critérios comprovados antes de aprovar.");return;}if(!approve&&!note){setError("Explique claramente ao usuário o que deve ser corrigido.");return;}setBusy(item.id);setError("");try{await reviewCampaignSubmission(item.id,approve,note,selected);await load();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy("");}};
  const metrics={pending:items.filter(i=>i.status==="pending").length,approved:items.filter(i=>i.status==="approved").length,rejected:items.filter(i=>i.status==="rejected").length,rewarded:referrals.filter(i=>i.status==="rewarded").length};
  return <section><div className="qa-page-header"><div><h1>Campanhas e afiliados</h1><p>Revisão auditável das missões, benefício único e acompanhamento do funil de indicações.</p></div><button className="qa-btn" onClick={()=>void load()}>Atualizar</button></div>
    {error&&<div className="qa-alert is-error" role="alert">{error}</div>}<div className="qa-metrics-grid"><div className="qa-metric-card"><div className="value">{metrics.pending}</div><div className="label">Aguardando análise</div></div><div className="qa-metric-card"><div className="value">{metrics.approved}</div><div className="label">Missões aprovadas</div></div><div className="qa-metric-card"><div className="value">{profiles.length}</div><div className="label">Afiliados</div></div><div className="qa-metric-card"><div className="value">{metrics.rewarded}</div><div className="label">Indicações premiadas</div></div></div>
    <div className="qa-form-row"><button className={`qa-btn ${tab==="missions"?"primary":""}`} onClick={()=>setTab("missions")}>Missões +30 dias</button><button className={`qa-btn ${tab==="affiliates"?"primary":""}`} onClick={()=>setTab("affiliates")}>Afiliados e indicações</button></div>
    {tab==="missions"?<><div className="qa-card"><div className="qa-form-row"><input aria-label="Buscar missão" placeholder="Buscar por usuário ou campanha" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Filtrar status" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todos os status</option><option value="pending">Em análise</option><option value="approved">Aprovadas</option><option value="rejected">Ajustes solicitados</option></select></div></div>{visible.map(item=>{const selected=criteria[item.id]||emptyCriteria();return <article className="qa-card" key={item.id}><div className="qa-card-header"><div><strong>{item.campaign_key}</strong><div className="qa-dim">Enviada em {date(item.submitted_at)} · reenvios: {item.resubmission_count||0}</div></div><span className={`qa-badge ${item.status}`}>{item.status}</span></div><p><b>Usuário:</b> <code>{item.user_id}</code></p><p><a href={item.social_post_url} target="_blank" rel="noreferrer">Abrir publicação social</a> · <a href={item.linkedin_post_url} target="_blank" rel="noreferrer">Abrir LinkedIn</a></p><div className="qa-review-feedback"><b>Feedback enviado</b><p>{item.product_feedback}</p></div>{item.status!=="approved"?<><fieldset className="qa-review-checklist"><legend>Comprovação obrigatória</legend>{checks.map(([key,label])=><label key={key}><input type="checkbox" checked={selected[key]} onChange={e=>setCriteria(current=>({...current,[item.id]:{...selected,[key]:e.target.checked}}))}/><span>{label}</span></label>)}</fieldset><label className="qa-review-notes">Retorno visível para o usuário<textarea rows={3} value={notes[item.id]||""} onChange={e=>setNotes(n=>({...n,[item.id]:e.target.value}))} placeholder="Explique a aprovação ou exatamente o que precisa ser ajustado."/></label><div className="qa-actions"><button className="qa-btn primary" disabled={busy===item.id} onClick={()=>void review(item,true)}>Aprovar e liberar +30 dias</button><button className="qa-btn danger" disabled={busy===item.id} onClick={()=>void review(item,false)}>Solicitar ajustes</button></div></>:<div className="qa-alert"><b>Recompensa liberada em {date(item.reviewed_at)}</b><p>{item.review_notes}</p><code>{item.reward_grant_id}</code></div>}</article>;})}{!visible.length&&<div className="qa-empty">Nenhuma missão encontrada.</div>}</>:<AffiliateManager profiles={profiles} referrals={referrals}/>}</section>;
}

function AffiliateManager({profiles,referrals}:{profiles:ReferralProfile[];referrals:Referral[]}) {
  const [query,setQuery]=useState(""); const [enabled,setEnabled]=useState<Record<string,boolean>>({}); const [busy,setBusy]=useState(""); const filtered=profiles.filter(p=>`${p.referral_code} ${p.user_id}`.toLowerCase().includes(query.toLowerCase()));
  const toggle=async(profile:ReferralProfile)=>{const current=enabled[profile.user_id]??profile.enabled;const reason=window.prompt(current?"Motivo da pausa (visível apenas no admin)":"Observação da reativação",profile.internal_notes||"");if(reason===null)return;setBusy(profile.user_id);try{await manageAffiliateProfile(profile.user_id,!current,reason);setEnabled(value=>({...value,[profile.user_id]:!current}));}finally{setBusy("");}};
  return <><div className="qa-card"><div className="qa-form-row"><input aria-label="Buscar afiliado" placeholder="Buscar código ou usuário" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="qa-table-wrap"><table className="qa-table"><thead><tr><th>Código</th><th>Afiliado</th><th>Indicados</th><th>Premiados</th><th>Desde</th><th>Status</th><th>Ação</th></tr></thead><tbody>{filtered.map(profile=>{const rows=referrals.filter(r=>r.referrer_user_id===profile.user_id);const active=enabled[profile.user_id]??profile.enabled;return <tr key={profile.user_id}><td><code>{profile.referral_code}</code></td><td><code>{profile.user_id}</code>{profile.internal_notes&&<div className="qa-dim">{profile.internal_notes}</div>}</td><td>{rows.length}</td><td>{rows.filter(r=>r.status==="rewarded").length}</td><td>{date(profile.created_at)}</td><td><span className={`qa-badge ${active?"active":"disabled"}`}>{active?"Ativo":"Pausado"}</span></td><td><button className={`qa-btn ${active?"danger":""}`} disabled={busy===profile.user_id} onClick={()=>void toggle(profile)}>{active?"Pausar":"Reativar"}</button></td></tr>;})}</tbody></table></div></div><div className="qa-card"><h2>Histórico de indicações</h2><div className="qa-table-wrap"><table className="qa-table"><thead><tr><th>Afiliado</th><th>Indicado</th><th>Status</th><th>Recompensa</th><th>Data</th></tr></thead><tbody>{referrals.map(row=><tr key={row.id}><td><code>{row.referrer_user_id}</code></td><td><code>{row.referred_user_id}</code></td><td><span className={`qa-badge ${row.status}`}>{row.status}</span></td><td>{row.reward_type||"—"}</td><td>{date(row.created_at)}</td></tr>)}</tbody></table></div></div>{!profiles.length&&<div className="qa-empty">Nenhum afiliado cadastrado.</div>}</>;
}
