import { useEffect, useRef, useState } from "react";
import { FiCopy, FiDownload, FiEdit2, FiExternalLink, FiRefreshCw, FiRotateCw, FiStar, FiTrash2 } from "react-icons/fi";
import { defaultBreakpointPresets, rotatePreset, validateDimensions, type BreakpointPreset } from "../services/breakpoints";

type Viewport = { preset: BreakpointPreset; url: string; zoom: number };
const presetsKey = "qtsBreakpointPresetsV1";

export function BreakpointViewer({ onMessage }: { onMessage: (message: string) => void }) {
  const [presets, setPresets] = useState<BreakpointPreset[]>([...defaultBreakpointPresets]);
  const [left, setLeft] = useState<Viewport>({ preset: defaultBreakpointPresets[1]!, url: "https://example.com", zoom: .6 });
  const [right, setRight] = useState<Viewport>({ preset: defaultBreakpointPresets[6]!, url: "https://example.com", zoom: .45 });
  const [sideBySide, setSideBySide] = useState(true); const [sameUrl, setSameUrl] = useState(true); const [syncScroll, setSyncScroll] = useState(false); const [revision, setRevision] = useState(0);
  const iframeRefs = useRef<Record<"left" | "right", HTMLIFrameElement | null>>({ left: null, right: null });
  useEffect(() => { void browser.storage.local.get(presetsKey).then((stored) => { if (Array.isArray(stored[presetsKey])) setPresets(stored[presetsKey] as BreakpointPreset[]); }); }, []);
  const savePresets = (next: BreakpointPreset[]) => { setPresets(next); void browser.storage.local.set({ [presetsKey]: next }); };
  const update = (side: "left" | "right", change: Partial<Viewport>) => { const setter = side === "left" ? setLeft : setRight; setter((current) => ({ ...current, ...change })); };
  const changeUrl = (side: "left" | "right", url: string) => { update(side, { url }); if (sameUrl) update(side === "left" ? "right" : "left", { url }); };
  const addCustom = () => { const dimensions = askDimensions(); if (!dimensions) { onMessage("Dimensões personalizadas inválidas."); return; } const next = { id: crypto.randomUUID(), name: `Custom ${dimensions.width}×${dimensions.height}`, ...dimensions, frame: "none" as const, favorite: false }; savePresets([...presets, next]); };
  const capture = async (target: "left" | "right" | "comparison") => { try { await captureElement(target === "comparison" ? "qts-device-grid" : `qts-device-${target}`, `breakpoint-${target}`); onMessage("Screenshot salvo."); } catch { onMessage("Não foi possível capturar. Mantenha o dispositivo visível na aba ativa."); } };
  const attachScroll = (side: "left" | "right", iframe: HTMLIFrameElement | null) => { iframeRefs.current[side] = iframe; if (!iframe || !syncScroll) return; try { const source = iframe.contentWindow!; source.addEventListener("scroll", () => { const target = iframeRefs.current[side === "left" ? "right" : "left"]?.contentWindow; if (target) target.scrollTo(source.scrollX, source.scrollY); }, { passive: true }); } catch { onMessage("Scroll sincronizado exige previews da mesma origem; mantendo rolagem independente."); } };
  return <div className="qtsBreakpointViewer"><div className="qtsControlMessage"><b>Simulação responsiva</b><p>Esta visualização simula dimensões no navegador atual. Hardware, sistema operacional e navegador móvel podem se comportar de forma diferente em um dispositivo real.</p></div><div className="qtsDrawerToolbar"><button onClick={() => setSideBySide((value) => !value)}>{sideBySide ? "Um dispositivo" : "Lado a lado"}</button><label><input type="checkbox" checked={sameUrl} onChange={(event) => setSameUrl(event.target.checked)} /> Mesma URL</label><label><input type="checkbox" checked={syncScroll} onChange={(event) => setSyncScroll(event.target.checked)} /> Sincronizar scroll</label><button onClick={addCustom}>Novo preset</button><button onClick={() => setRevision((value) => value + 1)}><FiRefreshCw /> Recarregar</button>{sideBySide && <button onClick={() => void capture("comparison")}><FiDownload /> Comparativo</button>}</div><div id="qts-device-grid" className={`qtsDeviceGrid ${sideBySide ? "isDouble" : ""}`}><DeviceView side="left" viewport={left} presets={presets} revision={revision} update={update} changeUrl={changeUrl} savePresets={savePresets} capture={capture} attachIframe={attachScroll} />{sideBySide && <DeviceView side="right" viewport={right} presets={presets} revision={revision} update={update} changeUrl={changeUrl} savePresets={savePresets} capture={capture} attachIframe={attachScroll} />}</div></div>;
}

function DeviceView({ side, viewport, presets, revision, update, changeUrl, savePresets, capture, attachIframe }: { side: "left" | "right"; viewport: Viewport; presets: BreakpointPreset[]; revision: number; update: (side: "left" | "right", change: Partial<Viewport>) => void; changeUrl: (side: "left" | "right", url: string) => void; savePresets: (next: BreakpointPreset[]) => void; capture: (target: "left" | "right" | "comparison") => Promise<void>; attachIframe: (side: "left" | "right", iframe: HTMLIFrameElement | null) => void }) {
  const select = (id: string) => { const preset = presets.find((item) => item.id === id); if (preset) update(side, { preset }); };
  const frameUrl = browser.runtime.getURL(`/frames/${viewport.preset.frame}.svg`);
  const previewUrl = safePreviewUrl(viewport.url);
  const replacePreset = (next: BreakpointPreset) => { savePresets(presets.map((item) => item.id === viewport.preset.id ? next : item)); update(side, { preset: next }); };
  const edit = () => { const dimensions = askDimensions(viewport.preset); if (!dimensions) return; const name = prompt("Nome do preset", viewport.preset.name)?.trim(); if (!name) return; replacePreset({ ...viewport.preset, ...dimensions, name: name.slice(0, 80) }); };
  const duplicate = () => { const next = { ...viewport.preset, id: crypto.randomUUID(), name: `${viewport.preset.name} cópia`, favorite: false }; savePresets([...presets, next]); update(side, { preset: next }); };
  const remove = () => { if (presets.length <= 1 || !confirm(`Excluir ${viewport.preset.name}?`)) return; const next = presets.filter((item) => item.id !== viewport.preset.id); savePresets(next); update(side, { preset: next[0]! }); };
  const move = (direction: -1 | 1) => { const index = presets.findIndex((item) => item.id === viewport.preset.id); const target = index + direction; if (target < 0 || target >= presets.length) return; const next = [...presets]; [next[index], next[target]] = [next[target]!, next[index]!]; savePresets(next); };
  return <section id={`qts-device-${side}`} className="qtsDevice"><div><select value={viewport.preset.id} onChange={(event) => select(event.target.value)}>{presets.map((preset) => <option key={preset.id} value={preset.id}>{preset.favorite ? "★ " : ""}{preset.name} · {preset.width}×{preset.height}</option>)}</select><button title="Editar" onClick={edit}><FiEdit2 /></button><button title="Duplicar" onClick={duplicate}><FiCopy /></button><button title="Excluir" onClick={remove}><FiTrash2 /></button><button title="Subir" onClick={() => move(-1)}>↑</button><button title="Descer" onClick={() => move(1)}>↓</button><button title="Trocar orientação" onClick={() => update(side, { preset: rotatePreset(viewport.preset) })}><FiRotateCw /></button><button title="Favoritar" onClick={() => replacePreset({ ...viewport.preset, favorite: !viewport.preset.favorite })}><FiStar /></button></div><div><input type="url" value={viewport.url} onChange={(event) => changeUrl(side, event.target.value)} /><button disabled={!previewUrl} onClick={() => previewUrl && window.open(previewUrl, "_blank", "noopener,noreferrer")}><FiExternalLink /></button><button onClick={() => void capture(side)}><FiDownload /></button><input type="range" min="0.25" max="1" step="0.05" value={viewport.zoom} onChange={(event) => update(side, { zoom: Number(event.target.value) })} /></div><div className={`qtsDeviceFrame ${viewport.preset.frame}`} style={{ width: viewport.preset.width * viewport.zoom, height: viewport.preset.height * viewport.zoom, backgroundImage: viewport.preset.frame === "none" ? undefined : `url(${frameUrl})` }}>{previewUrl ? <iframe ref={(node) => attachIframe(side, node)} onLoad={(event) => attachIframe(side, event.currentTarget)} key={`${revision}:${previewUrl}`} src={previewUrl} title={`${viewport.preset.name} preview`} sandbox="allow-forms allow-modals allow-popups allow-same-origin allow-scripts" referrerPolicy="no-referrer" style={{ width: viewport.preset.width, height: viewport.preset.height, transform: `scale(${viewport.zoom})`, transformOrigin: "top left" }} /> : <p>Informe uma URL HTTP ou HTTPS válida.</p>}</div><small>Se o site bloquear iframe por CSP ou X-Frame-Options, use abrir externamente.</small></section>;
}

function askDimensions(current?: BreakpointPreset): { width: number; height: number } | null { const width = Number(prompt("Largura entre 200 e 7680", String(current?.width ?? 375))); const height = Number(prompt("Altura entre 300 e 4320", String(current?.height ?? 667))); return validateDimensions(width, height) ? { width, height } : null; }
function safePreviewUrl(value: string): string | null { try { const url = new URL(value); return url.protocol === "http:" || url.protocol === "https:" ? url.href : null; } catch { return null; } }
async function captureElement(id: string, name: string): Promise<void> {
  const element = document.getElementById(id); if (!element) throw new Error("missing_target");
  const response = await browser.runtime.sendMessage({ type: "qts:capture-visible-tab" }) as { dataUrl?: string }; if (!response.dataUrl) throw new Error("capture_failed");
  const image = new Image(); image.src = response.dataUrl; await image.decode(); const rect = element.getBoundingClientRect(); const scale = image.naturalWidth / window.innerWidth;
  const canvas = document.createElement("canvas"); canvas.width = Math.max(1, Math.round(rect.width * scale)); canvas.height = Math.max(1, Math.round(rect.height * scale));
  canvas.getContext("2d")!.drawImage(image, rect.left * scale, rect.top * scale, rect.width * scale, rect.height * scale, 0, 0, canvas.width, canvas.height);
  const blob = await new Promise<Blob>((resolve, reject) => canvas.toBlob((value) => value ? resolve(value) : reject(new Error("encode_failed")), "image/png")); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `${name}-${Date.now()}.png`; link.click(); URL.revokeObjectURL(url);
}
