import { useEffect, useState } from "react";
import { FiCheckCircle, FiExternalLink, FiKey, FiLock, FiTrash2, FiUploadCloud } from "react-icons/fi";
import { maskedConvertioKey, removeConvertioKey, saveConvertioKey } from "../services/convertio";

export function ConvertioSettings({ onMessage }: { onMessage: (message: string) => void }) {
  const [key, setKey] = useState(""); const [masked, setMasked] = useState<string | null>(null); const [accepted, setAccepted] = useState(false);
  useEffect(() => { void maskedConvertioKey().then(setMasked); }, []);
  const save = async () => {
    if (!accepted) { onMessage("Confirme que entendeu o envio ao serviço externo e possíveis custos."); return; }
    try { const granted = await browser.permissions.request({ origins: ["https://api.convertio.co/*"] }); if (!granted) throw new Error("Permissão para a API Convertio não concedida."); await saveConvertioKey(key); setMasked(await maskedConvertioKey()); setKey(""); onMessage("Chave salva somente neste navegador."); } catch (error) { onMessage(error instanceof Error ? error.message : "Não foi possível salvar a chave."); }
  };
  return <section className="qtsIntegrationPage"><header><span><FiUploadCloud /></span><div><small>INTEGRAÇÃO OPCIONAL</small><h2>Convertio para GIF</h2><p>Converta gravações em GIF somente quando precisar compartilhar evidências leves.</p></div>{masked && <em><FiCheckCircle /> Conectado</em>}</header><div className="qtsIntegrationGrid"><article className="qtsIntegrationCard"><h3><FiKey /> Credencial da API</h3><p>A chave é armazenada localmente neste perfil do Chrome e nunca é enviada ao nosso backend.</p>{masked && <div className="qtsConfiguredKey"><FiLock /><span><small>Chave configurada</small><code>{masked}</code></span><button onClick={() => void removeConvertioKey().then(() => { setMasked(null); onMessage("Chave Convertio removida."); })}><FiTrash2 /> Remover</button></div>}<label><span>{masked ? "Substituir API key" : "API key da Convertio"}</span><input type="password" autoComplete="off" value={key} onChange={(event) => setKey(event.target.value)} placeholder="Cole a chave sem espaços" /></label><label className="qtsConsentCard"><input type="checkbox" checked={accepted} onChange={(event) => setAccepted(event.target.checked)} /><span><b>Confirmo o processamento externo</b><small>Entendo que o vídeo será enviado à Convertio somente por minha ação, poderá consumir créditos da minha conta e a conversão poderá ser cancelada.</small></span></label><button className="qtsPrimary qtsIntegrationSave" disabled={!key.trim() || !accepted} onClick={() => void save()}><FiCheckCircle /> Validar e salvar integração</button></article><aside><h3>Como funciona</h3><ol><li><b>1</b><span><strong>Grave localmente</strong><small>A captura permanece no navegador.</small></span></li><li><b>2</b><span><strong>Solicite o GIF</strong><small>O upload ocorre somente após confirmação.</small></span></li><li><b>3</b><span><strong>Baixe e limpe</strong><small>O arquivo remoto é removido ao concluir ou cancelar.</small></span></li></ol><a href="https://developers.convertio.co/api/docs/" target="_blank" rel="noreferrer">Abrir documentação oficial <FiExternalLink /></a></aside></div></section>;
}
